site_name: Simulation Software Engineering

repo_name:  Simulation-Software-Engineering/homepage
repo_url: https://github.com/Simulation-Software-Engineering/homepage

theme:
  name: material
#  icon:
#    logo: Simulation-Software-Engineering/homepage
#    repo: fontawesome/brands/git-alt
  palette:
    primary: blue
    accent: blue
  features:
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ajaust
    - icon: fontawesome/brands/github
      link: https://github.com/uekerman
